# Aviation 101


:::{.callout-note}
**Author's note**: This part brings in the minimal background necessary to comprehend the
aviation world, including vocabulary and historical aspects which led to
the current situation.

not sure this is an own part, but it might be good to have a
small section speaking about aviation vs air transport, airspace
vs controlled/ATC, airport airside (landside or why we skip this),
active/secondary surveillance, \.... This might be the place to
also speak about trajectory \~ flight and other basics.
:::

## The history of aviation

## Airspace
* Definition of the term 'airspace'
* Airspace classes (A, B, C, D, E, F, G), controlled vs. uncontrolled airspace
* Airspace around airports (TMAs, CTRs)

## Aerodromes
This section gives a short overview on the most important concepts and terms:
* Definition of the term 'aerodrome'
* Types of aerodromes
* Most important components of an aerodrome, i.e., runway, taxiways, aprons, terminal buildings, etc.
* Airside vs. Landside

## Air Navigation Services (ANS)
* Aeronautical Information Management (AIM)
* Air Traffic Management (ATM)
* Meteorological Services (MET)
* Communication, Navigation, Surveillance (CNS)
* Search and Rescue (SAR)




