# Aeronautical information

::: {.callout-tip}
Author: ?
:::

::: {.infobox .note}
**Author's note**: This part goes through all the most commonly used data formats in the
aviation and ATM data analysis community.

Airspaces & / or aeronautical information in general (AIRAC):

* airport information:
    - ARP
    - runway thresholds
    - parking positions]
* Published Points
* Routes
* SID / STAR
* ...
:::




Fatal events both en-route (mid-air collisions) and on the ground (landing or crashes)
are at the origin of modern Air Traffic Control.
In particular, flight plan filing was devised as a means to let
controllers know where an aircraft was supposed to be and eventually be able
to deconflict its trajectory with other flights nearby.
The flight plan together with latest position reports was (and still is)
the best information available to eventually launch search and rescue operations.

In principle, a flight plan could simply be a list of 4D coordinates (3D + time),
but it surely was computationally and practically difficult to use it as such
by ATC controllers who had to manually follow up airborne flights.
So the en-route network was designed to have fixed and limited  paths to follow.
In doing so the probability of conflicts was increased but at the same time such
network improves the efficiency in spotting them.


## Airports, Points and Routes

:::{.callout-note collapse=false appearance='default' icon=true}
## TODO
- Check nomenclature, i.e. [Significant Point](https://aviation.stackexchange.com/a/80480), ...
- References:
  * ICAO Doc 4444
  * Rules of the Air <https://www.pilot18.com/wp-content/uploads/2017/10/Pilot18.com-ICAO-Annex-2-Rules-of-air.pdf>
  * <https://skybrary.aero/articles/waypoint>
  * <https://www.skybrary.aero/articles/ats-route>
  * EUROCONTROL HMI:
    1. NVA Navigation Aid
    1. PWP Published Way Point
    1. ICP Internal Point
    1. GEO GEO Point
    1. RFP Reference Point
    1. RAD RADAR Point
    1. TER Terminal Point
    1. BDY Boundary Point
    1. DME Distance Measuring Equipment
    1. VOR VHF Omni-directional radio Range
    1. VOR_DMEco-located VHF Omni-directional radio Range and Distance Measuring Equipment
    1. VOR_DME_NDB co-located VHF Omni-directional radio Range,
       Distance Measuring Equipment and Non-Directional Beacon
    1. VORTAC co-located VHF Omni-directional radio Range and TACtical Air Navigator
    1. DVOR Doppler VHF Omni-directional radio Range
    1. DVOR_DME co-located Doppler VHF Omni-directional radio Range and Distance Measuring Equipment
    1. DVOR_DME_NDBco-located Doppler VHF Omni-directional radio Range,
       Distance Measuring Equipment and Non-Directional Beacon)
    1. DVORTAC co-located Doppler VHF Omni-directional radio Range and TACtical Air Navigator
    1. ILS Instrument Landing System
    1. ILS_DME co-located Instrument Landing System and Distance Measuring Equipment
    1. ILS_LLZ co-located Instrument Landing System and Localizer
    1. ILS_LLZ_DME co-located Instrument Landing System, Localizer and Distance Measuring Equipment
    1. LLZ Localizer
    1. LLZ_DME co-located Localizer and Distance Measuring Equipment
    1. L Locator
    1. LI Inner Locator
    1. LM Middle Locator
    1. LO Outer Locator
    1. L_DME co-located Locator and Distance Measuring Equipment
    1. MLS Microwave Landing System
    1. NDB Non-Directional Beacon
    1. NDB_DME co-located Non-Directional Beacon and Distance Measuring Equipment

:::


The aviation route network is characterized by the definition of geographical
points, waypoints, and segments connecting them, route segments.

## Airspaces

:::{.callout-note collapse=false appearance='default' icon=true}
## TODO
   * different types of airspaces
      - from EUROCONTROL CHMI:
         a) SECTOR ES Elementary Airspace Sector
         b) SECTOR CS Collapsed Sector
         c) AUA ATC Unit Airspace
         d) CLUSTER Airspace Cluster
         e) SECTOR CONFIGURATION Sector Configuration
         f) AUAGATC Unit Airspace Group
         g) REGION Region
         h) IR Information Region
         i) NAS National Airspace
         j) AREA Area
         k) ERSA Elementary Restricted Airspace
         l) CRSA Composed Restricted Airspace
         m) AOI Area of Interest
         n) AOP Area of Protection
         o) ERAS Elementary Regulated Airspace
         p) CRAS Composed  Regulated Airspace
         q) AIRBLOCK Airblock
      - from Skybrary: <https://skybrary.aero/articles/classification-airspace>
:::


