---
title: Aerodromes and airports
output-file: aerodrome
author: Manuel Waltert
---
<!--Definition of term "aerodrome"-->
In ICAO Annex 14, the term **aerodrome** is defined as *"a defined area on land or water (including any buildings, installations and equipment) intended to be used either wholly or in part for the arrival, departure and surface movement of aircraft."* The reference to a *defined area* suggests that aerodromes are systems, designed and operated for the purpose of both facilitating the efficient handling of departing and arrving aircraft as well as providing all the processes required by aircraft between take-off and landing. As such, aerodromes do not only have to be land-based. Rather, water-based as well as floating structures, such as oil rigs or ships, can be considered as aerodromes. Consequently, aerodromes are not solely designed for fixed-wing aircraft, but also for rotary-wing vehicles. 

<!--Types of Aerodromes-->
Since aerodromes have such a diverse range of applications, a distinction is made between different types of aerodromes. This typification often varies from country to country or region to region and (unfortunately) is not internationally standardised. For instance, an aerodrome designed for use of rotary-wing aircraft, i.e., helicopters, is called a **heliport**. A facility specifically designed for seaplanes and/or amphibian vehicles, which are aircraft able to land both on land and on water, is referred to as a **water aerodrome**. An aerodrome designed for the usage of small, often propeller-driven, general aviation aircraft, is called an **airstrip**, an **airfield**, or **small aerodrome**. Quite frequently, these type of aerodromes are equipped with a grass runway. An aerodrome used exclusively for military air operations is called a **military air base**. Finally, **civil airports** refer to facilities which are mainly available to commercial air transport. This refers to flight movements in which passengers (or cargo) are transported by an airline for a fee. For the remainder of this section, the focus is primarily on land-based **civil airports** designed for use by fixed-wing aircraft.

According to European Regulation (EU) 2018/1139, all aerodromes in the European Union which

i. are open to public use;  
ii. serve commercial air transport; and  
iii. have a paved instrument runway of 800 metres or more, or exclusively serve helicopters using instrument approach or departure procedures; 

fall under the scope of the *Basic Regulation* (BR) of the **European Union Aviation Safety Agency** and its *Implementing Rules* (IR). These aerodromes are therefore subject to legally binding requirements that define how they must be designed, maintained, and operated. Aerodromes which handle no more than 10'000 commercial air transport passengers per year and no more than 850 movements related to cargo operations per year can be excempted from an applicablility of Regulation (EU) 2018/1139. For this reason, EASA publishes on its website [a list of aerodromes](https://www.easa.europa.eu/en/datasets/aerodromes-falling-scope-regulation-eu-20181139) specifying for which Regulation (EU) 2018/1139 is applicable and which aerodromes are exempted.

Aerodromes falling under the scope of the *basic regulation* must be certified. In simple terms, in this certification procedure an aerodrome must show how and in what way the *certification specifications* of EASA are complied with or, if they cannot be complied with, what measures are/were taken to ensure an equivalent level of safety. The demonstration of an equivalent level of safety is particularly important for aerodromes that have grown over many decades and can only make certain changes to the facilities to ensure specifications under great financial constraints or not at all, e.g., due to topographical reasons.

Certification specifications are stipulated by the EASA in the [**CS-ADR** document](https://www.easa.europa.eu/en/certification-specifications/cs-adr-dsn-aerodromes-design) for aerodromes and the [**CS-HPT** document](https://www.easa.europa.eu/en/document-library/certification-specifications/group/cs-hpt-dsn-heliports-design) for heliports. These certification specifications define to a great detail, how large parts of an aerodrome and a heliport have to be designed and built. For example, CS-ADR defines how runways, taxiways, or aprons of an aerdrome must be designed, sized, or marked.

## Anatomy of an aerodrome
An aerodrome can be divided into two distinct parts: the **airside** and the **landside**. Although there are different definitions for these two terms both in the literature and in the industry, we use the following definitions in this document:

* The **airside** of an aerodrome covers all areas which can be used by aircraft. This includes both the maneouvring area as well as the apron(s) of an aerodrome.
* The **landside** of an aerodrome covers all areas which are not accessible for aircraft. This includes the terminals, docks, the baggage handling system (BHS), ground access infrastructure, etc.

In the following, aerodrome infrastructure and components associated to the airside and the landside are introducted and described in more detail.

### Airside components of an aerodrome
<!--runway, taxiways, aprons-->
The airside of an aerodrome consists of the maneouvring area and the apron(s). In CS ADR-DSN.A.002, the **manevouvring area** is defined as the *"part of an aerodrome to be used for the take-off, landing and taxiing of aircraft, excluding aprons"*. Consequently, the maneouvring area consists of both runway(s) and taxiway(s). As such, CS ADR-DSN.A.002 defines a **runway** as a *"rectangular area on a land aerodrome prepared for the landing and take-off of aircraft"*, while a **taxiway** is a *"defined path on a land aerodrome established for the taxiing of aircraft and intended to provide a link between one part of the aerodrome and another"*. Finally, the **apron(s)** of an aerodrome are according to CS ADR-DSN.A.002 defined as an *"area intended to accommodate aircraft for purposes of loading or unloading passengers, mail or cargo, fuelling, parking, or maintenance"*.

<!--Aerodrome Reference Code-->
::: {.callout-note}
Facilities on the airside of an aerodrome are designed and sized for a **critical aircraft**, which is either a real-world of fictitious aircraft. Consequently, aircraft that put higher requirements to the facilities than the critical aircraft, e.g., greater weight, longer wingspan, etc., cannot use the airport or parts of the airport. To prevent each aerodrome from having to describe individually which critical aircraft was used, an **aerodrome reference code** (ARC) which describes certain characteristics of the critical aircraft applied is used instead. As such, the ARC consists of two components: an aerodrome code number and a code letter. The **aerodrome code number** describes the reference field length of the critical aircraft in four categories:

| Aerodrome code number | Reference field length       |
|:---------------------:|------------------------------|
| 1                     | $<$ 800 m                    |
| 2                     | $\geq$ 800 m and $<$ 1200 m  |
| 3                     | $\geq$ 1200 m and $<$ 1800 m |
| 4                     | $\geq$ 1800 m                |
: Aerodrome code number (CS ADR-DSN.A.005) {#tbl-arc-number}


The **aerodrome code letter** describes in six categories the maximum wingspan of the critical aircraft:

| Aerodrome code letter | Maximum wingspan       |
|:---------------------:|------------------------|
| A                     | $<$ 15 m                 |
| B                     | $>$ 15 m and $\leq$ 24 m |
| C                     | $>$ 24 m and $\leq$ 36 m |
| D                     | $>$ 36 m and $\leq$ 52 m |
| E                     | $>$ 52 m and $\leq$ 65 m |
| F                     | $>$ 65 m and $\leq$ 80 m |
: Aerodrome code letter (CS ADR-DSN.A.005) {#tbl-arc-letter}


For example, an aerodrome with an ARC of "4F" can be used by aircraft with a reference field length of more than 1800m and a wingspan of up to 80m, whereas on an aerodrome with an ARC of "4E" the wingspan is limited to 65m.
:::

#### Runways
Runways facilitate the landing and taking-off of aircraft. In terms of their geometric properties, a runway can be described in terms of its width, slope(s), length, and orientation. 

The **width** of a runway is defined in CS ADR-DSN.B.045 and is usually measured from at outside edges of the runway. As such, the width of the runway depends both on the Aerodrome Code Letter (see Table @tbl-arc-number) and the Outer Main Gear Wheel Span (OMGWS) of the critical aircraft as indicated in Table @tbl-rwy-width. Thereby, the OMWGS describes the distance between the outside edges of the main gear wheels of the critical aircraft.

| Aerodrome Code number | 4.5m $\leq$ OMGWS | 4.5m $\leq$ OMGWS $<$ 6m | 6m $\leq$ OMGWS $<$ 9m | 9m $\leq$ OMGWS $<$ 15m |
|:---------------------:|------------------:|-------------------------:|-----------------------:|------------------------:|
| 1                     | 18m               | 18m                      | 23m                    | -                       |
| 2                     | 23m               | 23m                      | 30m                    | -                       |
| 3                     | 30m               | 30m                      | 30m                    | 45m                     |
| 4                     | -                 | -                        | 45m                    | 45m                     |
: Runway width (CS ADR-DSN.B.045) {#tbl-rwy-width}

The **slope** of a runway is specified both longitudinally and transversely. The **longitudinal slope** refers to the slope of the runway along its longitudinal axis. The average longitudinal slope of a runway is determined "by dividing the difference between the maximum and minimum elevation along the runway centre line by the runway length" (CS ADR-DSN.B.060). Additionally, CS ADR-DSN.B.060 specifies the maximum longitudinal slope which must not been exceeded in any portion of the runway. Finally, airport designers must ensure that the change in slope between two consecutive portions of the runway is below a certain value. The applicable values for the average longitudinal slope, maximum longitudinal slope, and the maximum longitudinal slope change, which all depend on the aerodrome code number (see Table @tbl-arc-number), are summarized in Table @tbl-rwy-lgnt-slope

| Aerodrome Code number | Average longitudinal slope | Maximum longitudinal slope | Maximum longitudinal slope change | 
|:---------------------:|---------------------------:|---------------------------:|----------------------------------:|
| 1                     | 2%                         | 2%                         | 2%                                |
| 2                     | 2%                         | 2%                         | 2%                                |
| 3                     | 1%                         | 1.5%                       | 1.5%                              |
| 4                     | 1%                         | 1.25%                      | 1.5%                              |
: Longitudinal slope of runways (CS ADR-DSN.B.060 & ADR-DSN.B.060) {#tbl-rwylgntslope}

 The **transverse slope** describes how a runway is sloped along its width to allow efficient drainage of rainwater. In practice, two different profile types of transverse slopes are used. *Chambered* profiles have their highest point at the centre of the runway, allowing water to drain to both sides of the runway, while the *single crossfall* profiles have thei highest elevation at one edge of the runway, allowing water to drain in the direction of the other edge. On runways of airports with an aerodrome code letter of A and B, see Table @tbl-arc-letter, the transverse slope must be between 1% and 2% according to CS ADR-DSN.B.080, on airports with an aerodrome code letter of C to F the transverse slope must be between 1% and 1.5%.

According to CS ADR-DSN.B.035, the **length** of a runway is to be sized in such a way that the operational requirements of the critical aeroplane for which the runway is designed can be met. In this context, the operational requirements are described by means of the following *declared distances*:

 * **Take-off run available** (TORA):
 * **Take-off distance available** (TODA):
 * **Accelerate-stop distance available** (ASDA):
 * **Landing distance available** (LDA):

The **orientation** of a runway describes its magnetic direction along its length. For example, a runway running in a north-south direction has an orientation of 360° or 180°, while a runway running in a west-east direction has an orientation of 090° or 270°. To enable pilots and air traffic controllers to identify runways unambiguously, each runway is given a **designator**. To this end, two-digit numbers are used as designators, e.g. 27, 07, 15, etc., which designate the nearest one-tenth of magnetic direction of a runway when viewed from the direction of approach. Example: If a pilot taxis onto runway 15 and aligns the aircraft so that its nose points in the direction of the other end of the runway, the aircraft's magnetic compass will indicate a value of 150° +/-5°. At airports with two parallel runways, the designator is supplemented with the letter "L" for "left" and "R" for "right". At airports with three parallel runways, the designator of the runway in the middle is supplemented with the letter "C" for "centre".

<!--Add Illustration for Runway Designation-->

The orientation of runways depends on a number of factors such as prevailing wind conditions, topographical conditions, etc. Flight crews are encouraged to take off and land into the wind whenever possible. For each aircraft type, there are clear guidelines that specify how strong the so-called crosswind component may be during a landing. For this reason, airport planners take into account long-term weather records on the strength and direction of the wind at an airport in order to orient the runway(s) in such a way that the crosswind componente (i.e. the amount of wind perpendicular to the runway) can be minimised. For this task, the so-called *usability factor* is used, which measures the percentage of time during which the operation of a runway is not restricted due to crosswind. According to GM1 ADR-DSN.B.015, a runway is considered optimally oriented if a usability factor of greater than or equal to 95% can be achieved. In addition to considering the wind direction, airport planners must also ensure that the runway can be operated safely. In this respect, topographical conditions (mountains, valleys, etc.) are of great importance. Furthermore, runways are often aligned in such a way that sensitive areas such as residential areas,  hospitals, etc. are not strongly affected by the emissions of air traffic. In places where several airports are located in a relatively small area (e.g. London, New York, Los Angeles, etc.), care is also taken when choosing the runway orientation that these airports do not influence each other's operations.

There is no requirement as to the **number** of runways an aerodrome must offer. Basically, the more runways an aerodrome is equipped, the greater its maximum capacity. At the same time, however, the provision of many runways is associated with high investments and operating costs. In theory, a distinction is made between the following generic airport layouts, which differ in the number of available runways and their orientation and arrangement:

* **Single runway**:
* **Open-V** or **Open-L runways**:
* **Intersecting** or **crossing runways**:
* **Parallel runways**:
* **Multiple parallel runways**:

Parallel runways --> Mode of operation, required distances between runways, and stagger

* Number (basic runway system layouts)
* Adjacent areas to runways
* Runway markings
* Runway lights
* Obstacles

#### Taxiways

* Taxiway dimensioning
* Taxiway marking, lighting, signage


Types of taxiways:
* "Normal" taxiways
* Apron stand taxilane
* Apron taxiway
* Rapid exit taxiway

#### Aprons

* Aprons
* Stands

### Landside components of an aerodrome
<!--terminals & docks-->
