---
title: Aerodromes and airports
author: Manuel Waltert
---

<!--Definition of term "aerodrome"-->
In \acr{ICAO} Annex 14, the term **aerodrome** is described as

> a defined area on land or water (including any buildings, installations and equipment) intended to be used either wholly or in part for the arrival, departure and surface movement of aircraft.

The reference to a *defined area* suggests that aerodromes are systems, designed and operated for the purpose of both facilitating the efficient handling of departing and arriving aircraft as well as providing all the processes required by aircraft between take-off and landing. As such, aerodromes do not only have to be land-based. Rather, water-based as well as floating structures, such as oil rigs or ships, can be considered as aerodromes. Consequently, aerodromes are not solely designed for fixed-wing aircraft, but also for rotary-wing vehicles. 

<!--Types of Aerodromes-->
Since aerodromes have such a diverse range of applications, a distinction is made between different types of aerodromes. This typification often varies from country to country or region to region and (unfortunately) is not internationally standardised. For instance, an aerodrome designed for use of rotary-wing aircraft, i.e., helicopters, is called a **heliport**. A facility specifically designed for seaplanes and/or amphibian vehicles, which are aircraft able to land both on land and on water, is referred to as a **water aerodrome**. An aerodrome designed for the usage of small, often propeller-driven, general aviation aircraft, is called an **airstrip**, an **airfield**, or **small aerodrome**. Quite frequently, these type of aerodromes are equipped with a grass runway. An aerodrome used exclusively for military air operations is called a **military air base**. Finally, **civil airports** refer to facilities which are mainly available to commercial air transport. This refers to flight movements in which passengers (or cargo) are transported by an airline for a fee. For the remainder of this section, the focus is primarily on land-based **civil airports** designed for use by fixed-wing aircraft.

According to European Regulation (EU) 2018/1139, all aerodromes in the European Union which

> i. are open to public use;  
> ii. serve commercial air transport; and  
> iii. have a paved instrument runway of 800 metres or more, or exclusively serve helicopters using instrument approach or departure procedures; 

fall under the scope of the \acr{BR} of the \acr{EASA} and its \acr{IR}. These aerodromes are therefore subject to legally binding requirements that define how they must be designed, maintained, and operated. Aerodromes which handle no more than 10,000 commercial air transport passengers per year and no more than 850 movements related to cargo operations per year can be exempted from an applicability of Regulation (EU) 2018/1139. For this reason, \acr{EASA} publishes on its website [a list of aerodromes](https://www.easa.europa.eu/en/datasets/aerodromes-falling-scope-regulation-eu-20181139) specifying for which Regulation (EU) 2018/1139 is applicable and which aerodromes are exempted.

Aerodromes falling under the scope of the *basic regulation* must be certified. In simple terms, in this certification procedure an aerodrome must show how and in what way the *certification specifications* of \acr{EASA} are complied with or, if they cannot be complied with, what measures are/were taken to ensure an equivalent level of safety. The demonstration of an equivalent level of safety is particularly important for aerodromes that have grown over many decades and can only make certain changes to the facilities to ensure specifications under great financial constraints or not at all, e.g., due to topographical reasons.

Certification specifications are stipulated by the \acr{EASA} in the [**CS-ADR** document](https://www.easa.europa.eu/en/certification-specifications/cs-adr-dsn-aerodromes-design) for aerodromes and the [**CS-HPT** document](https://www.easa.europa.eu/en/document-library/certification-specifications/group/cs-hpt-dsn-heliports-design) for heliports. These certification specifications define to a great detail, how large parts of an aerodrome and a heliport have to be designed and built. For example, CS-ADR defines how runways, taxiways, or aprons of an aerodrome must be designed, sized, or marked.

An aerodrome can be divided into two distinct parts: the **airside** and the **landside**. Although there are different definitions for these two terms both in the literature and in the industry, we use the following definitions in this document:

* The **airside** of an aerodrome covers all areas which can be used by aircraft. This includes both the manoeuvring area as well as the apron(s) of an aerodrome.
* The **landside** of an aerodrome covers all areas which are not accessible for aircraft. This includes the terminals, docks, the baggage handling system (BHS), ground access infrastructure, etc.

In the following, aerodrome infrastructure and components associated to the airside and the landside are introduced and described in more detail.

The following pages separate the aerodrome into its main functional subsystems: [runways](runways.qmd), [taxiways, aprons, and stands](taxiways-aprons-stands.qmd),  [passenger buildings](passenger-buildings.qmd), [baggage handling systems](baggage-handling-systems.qmd), [aerodrome ground access](aerodrome-ground-access.qmd), [airport capacity](airport-capacity.qmd), [delay and demand management](demand-management.qmd), and [airport operations](airport-operations.qmd).

## Airside components of an aerodrome
<!--runway, taxiways, aprons-->
The airside of an aerodrome consists of the manoeuvring area and the apron(s). In CS ADR-DSN.A.002, the **manoeuvring area** is defined as the *"part of an aerodrome to be used for the take-off, landing and taxiing of aircraft, excluding aprons"*. Consequently, the manoeuvring area consists of both runway(s) and taxiway(s). As such, CS ADR-DSN.A.002 defines a **runway** as a *"rectangular area on a land aerodrome prepared for the landing and take-off of aircraft"*, while a **taxiway** is a *"defined path on a land aerodrome established for the taxiing of aircraft and intended to provide a link between one part of the aerodrome and another"*. Finally, the **apron(s)** of an aerodrome are according to CS ADR-DSN.A.002 defined as an *"area intended to accommodate aircraft for purposes of loading or unloading passengers, mail or cargo, fuelling, parking, or maintenance"*.

<!--Aerodrome Reference Code-->
::: {.callout-tip}
#### Critical aircraft, aerodrome reference code, and aerodrome code number
Facilities on the airside of an aerodrome are designed and sized for a **critical aircraft**, which is either a real-world or fictitious aircraft. Consequently, aircraft that put higher requirements to the facilities than the critical aircraft, e.g., greater weight, longer wingspan, etc., cannot use the airport or parts of the airport. To prevent each aerodrome from having to describe individually which critical aircraft was used, an **aerodrome reference code** (ARC) which describes certain characteristics of the critical aircraft applied is used instead. As such, the ARC consists of two components: an aerodrome code number and a code letter. The **aerodrome code number** describes the reference field length of the critical aircraft in four categories:

| Aerodrome code number | Reference field length       |
|:---------------------:|------------------------------|
| 1                     | $<$ 800 m                    |
| 2                     | $\geq$ 800 m and $<$ 1200 m  |
| 3                     | $\geq$ 1200 m and $<$ 1800 m |
| 4                     | $\geq$ 1800 m                |
: Aerodrome code number (CS ADR-DSN.A.005) {#tbl-arc-number}


The **aerodrome code letter** describes in six categories the maximum wingspan of the critical aircraft:

| Aerodrome code letter | Maximum wingspan       |
|:---------------------:|------------------------|
| A                     | $<$ 15 m                 |
| B                     | $>$ 15 m and $\leq$ 24 m |
| C                     | $>$ 24 m and $\leq$ 36 m |
| D                     | $>$ 36 m and $\leq$ 52 m |
| E                     | $>$ 52 m and $\leq$ 65 m |
| F                     | $>$ 65 m and $\leq$ 80 m |
: Aerodrome code letter (CS ADR-DSN.A.005) {#tbl-arc-letter}

For example, an aerodrome with an ARC of "4F" can be used by aircraft with a reference field length of more than 1800 m and a wingspan of up to 80 m, whereas on an aerodrome with an ARC of "4E" the wingspan is limited to 65 m.
:::

## Landside components of an aerodrome

The **landside** includes the airport components used by passengers, baggage, staff, goods, and vehicles before or after the aircraft movement itself. In the rest of this aerodrome sequence, landside infrastructure is introduced through passenger buildings, baggage handling systems, and ground access.

## Glossary {.unnumbered}
