---
title: Anatomy of an aircraft
output-file: aircraft
---

## Aircraft categorisation

There exists a wide variety of air vehicles that can be grouped in broad categories.
ICAO refers to aircraft category as "a classification of aircraft according to specified characteristics".
The aircraft categorisation has relevance for the flight training and associated licensing, but also for the operation of the aircraft in terms of equipment, operating capabilities and limits, and access to airspace.
Thus, aircraft categorisation comprises also the intended use and operating environment.

aircraft / air vehicle
* lighter than air
  * airships and ballons
* heavier than air
  * aeroplane or airplane: engine-driven, fixed-wing, heavier-than-air aircraft that achieves flight through the reaction between the air and its wings
  * rotorcraft: engine-driven, rotating wing/rotors achieving lift
  * glider: non-powered fixed-wing designed to use air currents and thermal lift through reaction between wing and air
  * powered parachute
  * rocket: aircraft propelled by expanding gases

Aircraft categorisation has therefore relevance for
* aircraft certification, i.e. the set of requirements to be met by design and demonstrated through flight test to obtain a "airworthiness certificate".
* pilot licensing, i.e. the set of requirements in terms of training (both ground school and flight training) to operate a specific category of aircraft in its intended use.

When speaking about aircraft categories often the terms (aircraft) class and (aircraft) type crop up. 
An aircraft class is a sub-division within a category with a focus on design and performance. For example, single-engine and multi-engine piston engine aircraft.
Aircraft type refers to the specific model of an aircraft.

In this chapter we focus on the conventional airplanes = powered heavier-than-air aircraft.

## Anatomy of an aircraft

Conceptually, a conventional aircraft (airplane) comprises the following parts

<!-- Note: might be good to have a principal graphic here -->

* fuselage - i.e., the planes body
* wings - an airfoil that produces the lift for flying
* tail (empennage) - serves to primarily stabilise the aircraft typically comprising a horizontal and vertical stabiliser (fin)
* engine/power plant - the power plant provides the energy neccessary to propel the aircraft
* landing gear (undercarriage) - the undercarriage that supports the aircraft when on the ground during taxiing, takeooff or landing.

The fuselage also hosts the cockpit

For the directional control of aircraft, movable parts allow the pilot/aircrew to steer the aircraft and change its direction of flight and attitude using aerodynamical forces.

* up-down movement control - "pitch": elevators. Elevators are (typically) attached to the horizontal stabiliser
* left-right turn control - "yaw": rudder. Surface attached to the vertical stabiliser
* longitudal "roll":  ailerons typically attached to the trailing edge of wings

APU, bleed, winglet etc.

Recognise an Airbus from a Boeing

## Flight mechanics

### Principle of flight

The movement of aircraft is governed by the interplay of four forces determining the trajectory of the aircraft.
These forces oppose each other. Conceptually, the flight movement is the result of balancing these forces with the aforementioned controls and available propelling power.

* lift
* weight
* thrust
* drag

Lift is generated as the result of the airspeed and the interaction of (predominantly) the wings with the passing air. 
Thus, thrust and angle of attack (aircraft attitude) are the main drivers of lift.

Weight is the force created by the mass of all components and the payload on board of an aircraft, e.g. including the passengers, cargo, fuel.

Thrust is generated by the aircraft power plant system. It acts in the forward direction.

Drag acts rearward and opposite to the directio of flight. Drag is composed of numerous parts. For example, some drag is produced by the shape of the aircraft (air drag). Another source of drag is the by-product of the lift force (induced drag).

Aircraft movement is therefore the resultant force of these four principle forces.
For example, for straight and level flight, i.e. the aircraft is neither climbing nor descending and neither accelerating or decelating.
Accordingly, all four forces are in balance acting in opposite directions. The lift vector is matching the weight vector, and thrust matches drag.

<!--  <https://skybrary.aero/articles/lift> -->


## Flight movement

A flight is characterised by the motion of an aircraft through the air from its starting point (aerodrome of departure) to its destination (aerodrome of destination). 
A series of terms exists to describe the (projected) path of movement for navigational purposes or in radio communication between pilot/aircrew and air trafic control.
Unfortunately, for the uninitiated, these terms are often used interchangeably, but have a distinct - and different - meaning.

* heading is the direction in which the longitudinal axis of an aircraft points. The heading is typically expressed in degrees from North (*). 
* track is the projected path of the aircraft on the surface of earth/map.
* bearing is simply the direction between two points. A bearing can thus be expressed as to-a-point or from-a-point. For navigation purposes bearings can be expressed in relation to North. Sometimes bearings are expressed in relation to the heading, i.e., relative bearing.

It is important to note that heading, track, and bearing are referenced to North. Thus, based on the underlying reference, this could be magnetic, true, or based on the chart grid. In various parts of the world there is a substantial offset between the magnetic and true North dircetion and will need to be considered/corrected for the respective navigational task at hand.
Since a magnetic compass is still an ultimate fallback instrument in aircraft, aircraft heading is predominantly used as magnetic heading.
And accordingly, charts showing true North grids show also isogonic lines with the difference between true and magnetic North (i.e., variation) to account for the variation when determining positions or planning a flight.

The difference between heading and track can be readily derived from a simple thought experiment. 
Let's assume an aircraft is flying from the East to the West:

* Without any wind influence, heading and track conincide. Strictly speaking we would have to plot positions of the aircraft flying a westerly heading (nose pointing to the west) and compare this to the heading.
* With wind influence, the heading would need to be corrected to negate the offset (drift) due to the wind. In this case the aircraft nose would be pointing further to the left (as we have wind from the South) to compensate the influence and continue (tracking) on a westerly (right-to-left) heading.

To support the flying task, navigational aids help pilots/aircrew to determine the position of the aircraft or proceed on an intended path.
For this purpose two additional terms are used to express the 'direction' of flight.

* course is the desired dirction of flight. For a flight segment the course presents the bearing to the next way point. 
* radial refers to the magnetic bearing from a navigation aid (e.g. VOR, TACAN), i.e., it reflects the magnetic bearing from the NAVAID to the aircraft.

The latter can be confusing as a the direction of flight and its position in relation from (or to) a NAVAID may not coincide.
Even if an aircraft tracks on the radial of a NAVAID it may be flying to (inbound) or from (outbound) the station (on this radial).
Absent of any wind influence, the (magnetic) heading would be the reverse course of a radial. 
<!-- maybe put a figure here --> If an aircraft flies towards a VOR on its (magnetic) radial 140, the (magnetic) compass heading reads 320.

see <https://skybrary.aero/articles/heading-track-and-radial>


## Speeds

* [ground speed](https://skybrary.aero/articles/ground-speed)
* [true airspeed](https://skybrary.aero/articles/true-airspeed)
* [indicated airspeed](https://skybrary.aero/articles/indicated-airspeed-ias)
* [calibrated airspeed](https://skybrary.aero/articles/calibrated-airspeed-cas)


## Aircraft Systems

This section comprises an overview of a series of aircraft systems.

### Collision Avoidance ACAS/TCAS

In order to ensure the safe travel of aircraft a series of safety systems were developed. **ACAS** (airborne collision avoidance system) is a generic term to describe systems that track the surrounding air traffic on the basis of their tansponders. Dependent on the determined distance and relative range rate and approach speed, a potential risk of collision can be detected.

TCAS (traffic alert and collision avoidance system) is an implementation of the ICAO ACAS standard. To our knowledge, there are no other implementation of ACAS. TCAS II is mandated in Europe since the year 2000 and addresses changes to the logic of the detection and resolution logic. We consider therefore both terms as interchangable. 

ACAS/TCAS issue two types of alerts:
* traffic advisory (TA) to support the pilot/aircrew to visually identify a potential conflicting flight
* resolution advisory (RA) is an avoidance maneuver. If both aircraft are equipped with an ACAS, the avoidance maneuvers are coordinated between the ACAS units via datalink.

